apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kcm-controller-manager
  name: kcm-controller-manager-metrics-monitor
  namespace: {{ .Values.kcm.namespace }}
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      interval: 30s
  selector:
    matchLabels:
      control-plane: kcm-controller-manager
