version: 2

project_name: kof-operator

builds:
  - id: amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -w=false
      - -s=false
    flags:
      - -trimpath
    main: ./cmd/main.go
    dir: kof-operator
    binary: bin/manager
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo
    builder: go

  - id: arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -w=false
      - -s=false
    flags:
      - -trimpath
    dir: kof-operator
    main: ./cmd/main.go
    binary: bin/manager
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo
    builder: go

changelog:
  disable: >-
    {{ if eq (index .Env "SKIP_SCM_RELEASE") "true" }}{{true}}{{ else }}{{false}}{{ end }}
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} by @{{ . }}{{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^(build|ci): "
      - "^ci\\("
      - "^chore:"
      - "^chore\\("
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "🚀 New Features 🚀"
      regexp: '^.*?(feat|enh|enhancement)(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "🔐 Security updates 🔐"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "🐛 Notable Fixes 🐛"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "📄 Documentation updates 📄"
      regexp: ^.*?docs?(\([[:word:]]+\))??!?:.+$
      order: 300
    - title: "✨ Notable Changes ✨"
      order: 9999

dockers:
  - id: linux-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.IMAGE_REPO }}:latest-amd64"
    skip_push: false
    dockerfile: "./kof-operator/goreleaser.dockerfile"
    use: buildx
    ids:
      - amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title="{{ .ProjectName }} - k0rdent Observability and FinOps"
      - --label=org.opencontainers.image.description="Image with k0rdent Observability and FinOps binary"
      - --label=org.opencontainers.image.url=https://github.com/k0rdent/kof
      - --label=org.opencontainers.image.source=https://github.com/k0rdent/kof
      - --label=org.opencontainers.image.version={{ .Env.VERSION }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/amd64

  - id: linux-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.VERSION }}-arm64"
      - "{{ .Env.IMAGE_REPO }}:latest-arm64"
    skip_push: false
    dockerfile: "./kof-operator/goreleaser.dockerfile"
    use: buildx
    ids:
      - arm64
    build_flag_templates:
      - --label=org.opencontainers.image.title="{{ .ProjectName }} - k0rdent Observability and FinOps"
      - --label=org.opencontainers.image.description="Image with k0rdent Observability and FinOps binary"
      - --label=org.opencontainers.image.url=https://github.com/k0rdent/kof
      - --label=org.opencontainers.image.source=https://github.com/k0rdent/kof
      - --label=org.opencontainers.image.version={{ .Env.VERSION }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/arm64/v8

docker_manifests:
  - name_template: "{{ .Env.IMAGE_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.VERSION }}-arm64"
    skip_push: false
    use: docker

  - name_template: "{{ .Env.IMAGE_REPO }}:latest"
    image_templates:
      - "{{ .Env.IMAGE_REPO }}:latest-amd64"
      - "{{ .Env.IMAGE_REPO }}:latest-arm64"
    skip_push: false
    use: docker

release:
  github:
    owner: k0rdent
    name: kof
