version: 2

project_name: kof-operator

git:
  tag_sort: -version:creatordate

builds:
  - id: amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -w=false
      - -s=false
    flags:
      - -trimpath
    main: ./cmd/main.go
    dir: kof-operator
    binary: bin/manager
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo
    builder: go

  - id: arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -w=false
      - -s=false
    flags:
      - -trimpath
    dir: kof-operator
    main: ./cmd/main.go
    binary: bin/manager
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo
    builder: go

changelog:
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} by @{{ . }}{{ end }}"
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "🚀 New Features 🚀"
      regexp: '^.*?(feat|enh|enhancement)(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "🐛 Notable Fixes 🐛"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "✨ More Improvements ✨"
      order: 9999
  disable: >-
    {{ if eq (index .Env "SKIP_SCM_RELEASE") "true" }}{{true}}{{ else }}{{false}}{{ end }}

dockers:
  - id: operator-linux-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:latest-amd64"
    skip_push: false
    dockerfile: "./kof-operator/goreleaser.dockerfile"
    use: buildx
    ids:
      - amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title="{{ .ProjectName }} - k0rdent Observability and FinOps"
      - --label=org.opencontainers.image.description="Image with k0rdent Observability and FinOps binary"
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.version={{ .Env.VERSION }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/amd64

  - id: operator-linux-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:{{ .Env.VERSION }}-arm64"
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:latest-arm64"
    skip_push: false
    dockerfile: "./kof-operator/goreleaser.dockerfile"
    use: buildx
    ids:
      - arm64
    build_flag_templates:
      - --label=org.opencontainers.image.title="{{ .ProjectName }} - k0rdent Observability and FinOps"
      - --label=org.opencontainers.image.description="Image with k0rdent Observability and FinOps binary"
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.version={{ .Env.VERSION }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/arm64/v8

  - id: otel-collector-linux-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:latest-amd64"
    skip_push: false
    dockerfile: "./docker/opentelemetry-collector-contrib/Dockerfile"
    use: buildx
    ids:
      - amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title="kof-opentelemetry-collector-contrib"
      - --label=org.opencontainers.image.description="opentelemetry-collector-contrib image with journalctl binary"
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.version={{ .Env.VERSION }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/amd64

  - id: otel-collector-linux-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:{{ .Env.VERSION }}-arm64"
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:latest-arm64"
    skip_push: false
    dockerfile: "./docker/opentelemetry-collector-contrib/Dockerfile"
    use: buildx
    ids:
      - arm64
    build_flag_templates:
      - --label=org.opencontainers.image.title="kof-opentelemetry-collector-contrib"
      - --label=org.opencontainers.image.description="opentelemetry-collector-contrib image with journalctl binary"
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}
      - --label=org.opencontainers.image.version={{ .Env.VERSION }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/arm64/v8
docker_manifests:
  - name_template: "{{ .Env.IMAGE_OPERATOR_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:{{ .Env.VERSION }}-arm64"
    skip_push: false
    use: docker

  - name_template: "{{ .Env.IMAGE_OPERATOR_REPO }}:latest"
    image_templates:
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:latest-amd64"
      - "{{ .Env.IMAGE_OPERATOR_REPO }}:latest-arm64"
    skip_push: false
    use: docker

  - name_template: "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:{{ .Env.VERSION }}-arm64"
    skip_push: false
    use: docker

  - name_template: "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:latest"
    image_templates:
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:latest-amd64"
      - "{{ .Env.IMAGE_OTEL_COLLECTOR_REPO }}:latest-arm64"
    skip_push: false
    use: docker
release:
  github:
    owner: "{{ .Env.GITHUB_OWNER }}"
    name: "{{ .Env.GITHUB_REPO_NAME }}"
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  prerelease: auto
  mode: replace
  footer: |
    ---
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}/compare/{{ .PreviousTag }}...{{ .Tag }}
  disable: >-
    {{ if eq (index .Env "SKIP_SCM_RELEASE") "true" }}{{true}}{{ else }}{{false}}{{ end }}
