{{- $global := .Values.global | default dict }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmauth.enabled }}
{{- if (index .Values "victoriametrics" "vmauth" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- $spec := deepCopy .Values.victoriametrics.vmauth.spec }}
  {{- if $global.registry }}
  {{- $_ := set $spec.image "repository" ( printf "%s/victoriametrics/vmalert" $global.registry) }}
  {{- end }}
  {{- if and $global.registry (ne $global.registry "docker.io") }}
  {{- $configReloaderImageTag := $spec.configReloaderImageTag | trimPrefix "quay.io/" }}
  {{- if le (regexFindAll "/" $configReloaderImageTag -1 | len) 1 }}
    {{- $_ := set $spec "configReloaderImageTag" (printf "%s/%s" $global.registry $configReloaderImageTag) }}
  {{- end }}
  {{- end }}
  {{- if not (get $spec.ingress.annotations "cert-manager.io/cluster-issuer") }}
  {{- $_ := set $spec.ingress.annotations "cert-manager.io/cluster-issuer" (include "cert-manager.cluster-issuer.name" $ )}}
  {{- $_ := mergeOverwrite $spec.ingress.annotations (include "cert-manager.acme-annotation" $ | fromYaml )}}
  {{- end }}
  {{- $extraEnvs := $spec.extraEnvs }}
  {{- $extraEnvs = append $extraEnvs (dict "name" "vm_httpAuth_username" "valueFrom" (dict "secretKeyRef" (dict "name" .Values.victoriametrics.vmauth.credentials.credentials_secret_name "key" .Values.victoriametrics.vmauth.credentials.username_key)))}}
  {{- $extraEnvs = append $extraEnvs (dict "name" "vm_httpAuth_password" "valueFrom" (dict "secretKeyRef" (dict "name" .Values.victoriametrics.vmauth.credentials.credentials_secret_name "key" .Values.victoriametrics.vmauth.credentials.password_key)))}}
  {{- $_ := set $spec "extraEnvs" $extraEnvs }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
