{{- $global := .Values.global | default (dict "image" dict) }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmcluster.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- $spec := deepCopy .Values.victoriametrics.vmcluster.spec }}
  {{- if $global.image.registry }}
  {{- $_ := set $spec.vminsert.image "repository" ( printf "%s/victoriametrics/vminsert" $global.image.registry) }}
  {{- $_ := set $spec.vmselect.image "repository" ( printf "%s/victoriametrics/vmselect" $global.image.registry) }}
  {{- $_ := set $spec.vmstorage.image "repository" ( printf "%s/victoriametrics/vmstorage" $global.image.registry) }}
  {{- end }}
  {{- if $global.storageClass }}
  {{- $_ := set $spec.vmselect.storage.volumeClaimTemplate.spec "storageClassName" $global.storageClass }}
  {{- $_ := set $spec.vmstorage.storage.volumeClaimTemplate.spec "storageClassName" $global.storageClass }}
  {{- end }}
  {{- $_ := set $spec.vmselect.extraArgs "vmalert.proxyURL" ( printf "http://vmalert-cluster.%s.svc:8080/" .Release.Namespace ) }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
