apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-managed0
  namespace: kcm-system
  labels:
    kof: "collector"
spec:
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: false
    region: us-east-2
    worker:
      instanceType: t3.small
    workersNumber: 3
    clusterLabels:
      k0rdent.mirantis.com/kof-storage-secrets: "true"
  template: aws-standalone-cp-0-1-2
  serviceSpec:
    priority: 100
    services:
      - name: cert-manager
        namespace: kof
        template: cert-manager-1-16-2
        values: |
          cert-manager:
            crds:
              enabled: true
      - name: kof-operators
        namespace: kof
        template: kof-operators-0-1-0
      - name: kof-collectors
        namespace: kof
        template: kof-collectors-0-1-0
        values: |
          global:
            clusterName: aws-managed0
          opencost:
            enabled: true
            opencost:
              prometheus:
                external:
                  url: "http://vmselect-cluster.kof:8481/select/0/prometheus"
              exporter:
                defaultClusterId: "aws-managed0"
          kof:
            basic_auth: false
            logs:
              endpoint: http://kof-storage-victoria-logs-single-server.kof:9428/insert/opentelemetry/v1/logs
            metrics:
              endpoint: http://vminsert-cluster.kof:8480/insert/0/prometheus/api/v1/write
