apiVersion: v2
name: kof-operators
description: A Helm chart that deploys opentelemetry-operator and prometheus CRDs
version: "1.2.0"
appVersion: "1.2.0"
dependencies:
  - name: grafana-operator
    version: "v5.18.0"
    repository: "oci://ghcr.io/grafana/helm-charts"
    condition: grafana-operator.enabled
  - name: opentelemetry-operator
    version: "0.84.2"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
  - name: prometheus-operator-crds
    version: "15.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-operator-crds.enabled
