prometheus-operator-crds:
  enabled: true
opentelemetry-operator:
  enabled: true
  manager:
    collectorImage:
      repository: "otel/opentelemetry-collector-contrib"
      tag: "0.123.0"
    createRbacPermissions: true
    extraArgs:
      - "--enable-go-instrumentation=true"
  clusterRole:
    create: true
  admissionWebhooks:
    autoGenerateCert:
      enabled: false
