cert-manager:
  enabled: true
  template: cert-manager-v1-16-4

kcm:
  namespace: kcm-system

collectors:
  opentelemetry-kube-stack:
    collectors:
      daemon:
        config:
          receivers:
            prometheus:
              api_server:
                server_config:
                  endpoint: ${env:OTEL_K8S_NODE_IP}:9090
            otlp:
              protocols:
                grpc:
                  endpoint: 127.0.0.1:4317
                http:
                  endpoint: 127.0.0.1:4318
          service:
            extensions:
              - basicauth/metrics
              - basicauth/logs
              - basicauth/traces
              - k8s_observer
              - file_storage/filelogreceiver
              - file_storage/filelogsyslogreceiver
              - file_storage/filelogk8sauditreceiver
            telemetry:
              metrics:
                address: ${env:OTEL_K8S_NODE_IP}:8888
                readers:
                  - pull:
                      exporter:
                        prometheus:
                          host: ${env:OTEL_K8S_NODE_IP}
                          port: 8888
        hostNetwork: true
        observability:
          metrics:
            disablePrometheusAnnotations: false
            enableMetrics: false
        podAnnotations:
          prometheus.io/ip4: ${env:OTEL_K8S_NODE_IP}
operators:
  grafana-operator:
    enabled: false
