# downloaded from
# https://github.com/fluxcd/flux2-monitoring-example/blob/main/monitoring/controllers/kube-prometheus-stack/kube-state-metrics-config.yaml
---
apiVersion: v1
data:
  flux.yaml: |
    ---
    kind: CustomResourceStateMetrics
    spec:
{{- if .Values.kcm.monitoring }}
      resources:
      - groupVersionKind:
          group: helm.toolkit.fluxcd.io
          version: v2
          kind: HelmRelease
        metricNamePrefix: gotk
        metrics:
          - name: "resource_info"
            help: "The current state of a Flux HelmRelease resource."
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [ metadata, name ]
            labelsFromPath:
              exported_namespace: [ metadata, namespace ]
              ready: [ status, conditions, "[type=Ready]", status ]
              suspended: [ spec, suspend ]
              revision: [ status, history, "0", chartVersion ]
              chart_name: [ status, history, "0", chartName ]
              chart_app_version: [ status, history, "0", appVersion ]
              chart_ref_name: [ spec, chartRef, name ]
              chart_source_name: [ spec, chart, spec, sourceRef, name ]
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          version: v1
          kind: GitRepository
        metricNamePrefix: gotk
        metrics:
          - name: "resource_info"
            help: "The current state of a Flux GitRepository resource."
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [ metadata, name ]
            labelsFromPath:
              exported_namespace: [ metadata, namespace ]
              ready: [ status, conditions, "[type=Ready]", status ]
              suspended: [ spec, suspend ]
              revision: [ status, artifact, revision ]
              url: [ spec, url ]
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          version: v1
          kind: Bucket
        metricNamePrefix: gotk
        metrics:
          - name: "resource_info"
            help: "The current state of a Flux Bucket resource."
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [ metadata, name ]
            labelsFromPath:
              exported_namespace: [ metadata, namespace ]
              ready: [ status, conditions, "[type=Ready]", status ]
              suspended: [ spec, suspend ]
              revision: [ status, artifact, revision ]
              endpoint: [ spec, endpoint ]
              bucket_name: [ spec, bucketName ]
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          version: v1
          kind: HelmRepository
        metricNamePrefix: gotk
        metrics:
          - name: "resource_info"
            help: "The current state of a Flux HelmRepository resource."
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [ metadata, name ]
            labelsFromPath:
              exported_namespace: [ metadata, namespace ]
              ready: [ status, conditions, "[type=Ready]", status ]
              suspended: [ spec, suspend ]
              revision: [ status, artifact, revision ]
              url: [ spec, url ]
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          version: v1
          kind: HelmChart
        metricNamePrefix: gotk
        metrics:
          - name: "resource_info"
            help: "The current state of a Flux HelmChart resource."
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [ metadata, name ]
            labelsFromPath:
              exported_namespace: [ metadata, namespace ]
              ready: [ status, conditions, "[type=Ready]", status ]
              suspended: [ spec, suspend ]
              revision: [ status, artifact, revision ]
              chart_name: [ spec, chart ]
              chart_version: [ spec, version ]
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          version: v1beta2
          kind: OCIRepository
        metricNamePrefix: gotk
        metrics:
          - name: "resource_info"
            help: "The current state of a Flux OCIRepository resource."
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [ metadata, name ]
            labelsFromPath:
              exported_namespace: [ metadata, namespace ]
              ready: [ status, conditions, "[type=Ready]", status ]
              suspended: [ spec, suspend ]
              revision: [ status, artifact, revision ]
              url: [ spec, url ]
{{- else }}
      resources: []
{{- end }}
kind: ConfigMap
metadata:
  labels:
    kube-state-metrics/custom-resource: "true"
  name: kube-state-metrics-crd-config-flux
  namespace: kof
