{
 "title": "KCM Controller Manager",
 "description": "Built from https://github.com/kubernetes-monitoring/kubernetes-mixin",
 "tags": [
  "kubernetes",
  "infrastucture"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "kcm-controller-manager : kcm-controller-manager-metrics-service"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{cluster=\"$cluster\", job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster=\"$cluster\", job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (cluster, instance, name)",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}instance}} {{\"{{\"}}name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{cluster=\"$cluster\", job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (cluster, instance, name)",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}instance}} {{\"{{\"}}name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=\"$cluster\", job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (cluster, instance, name, le))",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}instance}} {{\"{{\"}}name}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\", instance=~\"$instance\",code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\", instance=~\"$instance\",code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\", instance=~\"$instance\",code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\", instance=~\"$instance\",code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\", job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{\"{{\"}}instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\", job=\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{\"{{\"}}instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{\"{{\"}}instance}}"
    }
   ]
  }
 ]
}