{{- if .Values.collectors.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-k8s-cluster
  namespace: {{ .Release.Namespace }}
spec:
  mode: deployment
  serviceAccount: "{{ .Release.Name }}-k8s-cluster-collector"
  {{- with .Values.collectors.k8scluster.env }}
  env: {{ toYaml . | nindent 4 }}
  {{- end }}
  config:
    receivers: {{ .Values.collectors.k8scluster.receivers | toYaml | nindent 6 }}
    processors: {{ .Values.collectors.k8scluster.processors | toYaml | nindent 6 }}
    {{- $exporters := include "cluster_exporters" (dict "kof" .Values.kof) | fromYaml }}
    exporters: {{ .Values.collectors.k8scluster.exporters | mergeOverwrite $exporters | toYaml | nindent 6 }}
    {{- $basic_auth_extensions := include "basic_auth_extensions" . | fromYaml }}
    extensions: {{ .Values.collectors.k8scluster.extensions | mergeOverwrite $basic_auth_extensions | toYaml | nindent 6 }}
    {{- $service := include "service" . | fromYaml }}
    service: {{.Values.collectors.k8scluster.service | mergeOverwrite $service | toYaml | nindent 6 }}
{{- end }}

