{{- if index .Values "external-dns" "enabled" | default false }}
{{- if index .Values "external-dns" "aws_static_credentials" | default false }}
apiVersion: v1
stringData:
  credentials: |
    [default]
    aws_access_key_id = {{ (index .Values "external-dns").aws_static_credentials.secrets.aws_access_key_id }}
    aws_secret_access_key = {{ (index .Values "external-dns").aws_static_credentials.secrets.aws_secret_access_key }}
kind: Secret
metadata:
  name: {{ (index .Values "external-dns").aws_static_credentials.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
{{- end }}
