{{- range .Values.grafana.datasources }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if .auth }}
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          key: {{ .auth.username_key }}
          name: {{ .auth.credentials_secret_name }}
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          key: {{ .auth.password_key }}
          name: {{ .auth.credentials_secret_name }}
    {{- end }}
  datasource:
    access: proxy
    isDefault: false
    name: {{ .name }}
    type: {{ .type }}
    url: {{ .url }}
    {{- if .auth }}
    basicAuth: true
    basicAuthUser: {{ printf "${%s}" .auth.username }}
    secureJsonData:
      basicAuthPassword: {{ printf "${%s}" .auth.password }}
    {{- end }}
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
---
{{- end }}

