{{ range $name, $value := .Values.intermediateCAs }}
{{- if $value.certificate }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-ca
  namespace: {{ $.Release.Namespace }}
spec:
  isCA: true
  commonName: {{ $name }} CA
  subject:
    organizations:
      - Istio
  secretName: {{ $.Release.Name }}-{{ $name }}-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $.Release.Name }}-root
    kind: Issuer
    group: cert-manager.io
{{- end }}
{{- if $value.issuer }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-ca
  namespace: {{ $.Release.Namespace }}
spec:
  ca:
    secretName: {{ $.Release.Name }}-{{ $name }}-ca
{{- end }}
{{- if $value.copy }}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: istio-{{ $name }}
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-itermediate-ca: {{ $name }}
  templateResourceRefs:
    - identifier: Secret
      resource:
        apiVersion: v1
        kind: Secret
        name: {{ $.Release.Name }}-{{ $name }}-ca
        namespace: {{ $.Release.Namespace }}
  policyRefs:
    - kind: ConfigMap
      name: {{ $.Release.Name }}-secret-template
      namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
