apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: kof-child-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
    matchExpressions:
      - key: "k0rdent.mirantis.com/istio-role"
        operator: DoesNotExist

  serviceSpec:
    templateResourceRefs:
      - identifier: ChildConfig
        resource:
          apiVersion: v1
          kind: ConfigMap
          name: kof-cluster-config-{{`{{ .Cluster.metadata.name }}`}}
          namespace: {{ .Values.kcm.namespace }}

    services:

      {{- if (index .Values "cert-manager" "enabled") }}
      - name: cert-manager
        namespace: {{ .Release.Namespace }}
        template: cert-manager-1-16-2
        values: |
          crds:
            enabled: true
      {{- end }}

      - name: kof-operators
        namespace: {{ .Release.Namespace }}
        template: kof-operators-{{ .Chart.Version | replace "." "-" }}

      - name: kof-collectors
        namespace: {{ .Release.Namespace }}
        template: kof-collectors-{{ .Chart.Version | replace "." "-" }}
        values: |
          {{`{{ $childClusterName := .Cluster.metadata.name }}`}}
          {{`{{ $writeMetricsEndpoint := getField "ChildConfig" "data.write_metrics_endpoint" }}`}}
          {{`{{ $readMetricsEndpoint := getField "ChildConfig" "data.read_metrics_endpoint" }}`}}
          {{`{{ $logsEndpoint := getField "ChildConfig" "data.write_logs_endpoint" }}`}}
          {{`{{ $tracesEndpoint := getField "ChildConfig" "data.write_traces_endpoint" }}`}}
          {{`{{ $patch := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-collectors-values" | default "{}" | fromYaml }}`}}
          {{`{{ $collectorsValues := `}}`
          {{ .Values.collectors | toYaml }}
          ` | fromYaml {{`}}`}}
          {{`{{ $values := printf `}}`{{`
          global:
            clusterName: %q
          kof:
            metrics:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
              endpoint: %q
            logs:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
              endpoint: %q
            traces:
              endpoint: %q
          opencost:
            enabled: true
            opencost:
              prometheus:
                username_key: username
                password_key: password
                existingSecretName: storage-vmuser-credentials
                external:
                  url: %q
              exporter:
                defaultClusterId: %q
          `}}`{{` $childClusterName $writeMetricsEndpoint $logsEndpoint $tracesEndpoint $readMetricsEndpoint $childClusterName | fromYaml }}`}}
          {{`{{ mergeOverwrite $values $collectorsValues $patch | toYaml | nindent 4 }}`}}
