{{- $global := .Values.global | default dict }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- $spec := deepCopy .Values.victoriametrics.vmalert.manager.spec }}
  {{- if $global.registry }}
  {{- $_ := set $spec.image "repository" ( printf "%s/prom/alertmanager" $global.registry) }}
  {{- if le (regexFindAll "/" $spec.configReloaderImageTag -1 | len) 1 }}
    {{- $_ := set $spec "configReloaderImageTag" (printf "%s/%s" $global.registry $spec.configReloaderImageTag) }}
  {{- end }}
  {{- end }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
