name: Test Helm Charts on KOF

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release/*
    paths:
      - "kof-operator/**"
      - "charts/**"
      - "!**.md"

env:
  GO_VERSION: "1.24"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Unit Tests
        working-directory: ./kof-operator
        run: make test

  lint-react:
    name: Run React Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./kof-operator/webapp/collector
        run: npm i
      - name: Run ESLint
        working-directory: ./kof-operator/webapp/collector
        run: npm run lint -- --max-warnings=0

  deploy:
    name: Deploy KOF & KCM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: kcm_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: k0rdent
          repo: kcm
          excludes: prerelease, draft
      - name: Checkout KCM Latest Release repo
        uses: actions/checkout@v4
        with:
          repository: k0rdent/kcm
          ref: ${{ steps.kcm_release.outputs.release }}
          path: kcm-repo
      - name: Restore KCM CLI Cache
        id: cache-kcm-cli
        uses: actions/cache/restore@v4
        with:
          path: kcm-repo/bin
          key: kcm-cli-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            kcm-cli-${{ runner.os }}-
      - name: Install KCM CLI
        run: |
          make -C kcm-repo cli-install
      - name: Save KCM CLI Cache
        uses: actions/cache/save@v4
        with:
          path: kcm-repo/bin
          key: kcm-cli-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}
      - name: Apply KCM Dev Configuration
        run: |
          make -C kcm-repo dev-apply
      - name: Install KOF CLI
        run: |
          make cli-install
      - name: Deploy local registry container
        run: |
          make registry-deploy
      - name: Push KOF Helm Charts
        run: |
          make helm-push
      - name: Deploy KOF Components
        run: |
          make dev-operators-deploy
          make dev-ms-deploy
          make dev-storage-deploy
          make dev-collectors-deploy
